f() -/>
  await g()
    catch err: err
