f() -/>
  x = await g()
    catch Error: false
