f() -/>
  x = await g()
    catch err: err
