try a catch err:
  | as {x}: x
