f() -/>
  await g() catch err: false
