f() -/>
  await g() catch Error: false
