try a catch err:
  | Error with { x }: x
